"""Builds outputs/reports/final_report.md, documentation/methodology_notes.md and README.md from result files."""
import pandas as pd
from . import config as C


def _md(df, cols=None, floatfmt=2):
    d = df.copy()
    if cols: d = d[cols]
    d = d.round(floatfmt).fillna("")
    head = "| " + " | ".join(map(str, d.columns)) + " |\n|" + "---|" * len(d.columns) + "\n"
    return head + "\n".join("| " + " | ".join(str(x).replace("|", "/").replace("\n", " ") for x in r) + " |" for r in d.values) + "\n"


def run():
    t = lambda n: pd.read_csv(C.TABLES / n); s = lambda n: pd.read_csv(C.STATS / n)
    hm = t("table12a_hypothesis_results.csv"); h = s("hypothesis_tests_H1_H7.csv")
    reg = s("regression_coefficients.csv"); dg = s("regression_diagnostics.csv"); sens = t("table12b_sensitivity_M1.csv")
    rel = t("table08_reliability.csv"); kmo = s("factorability_kmo_bartlett.csv").iloc[0]; eig = s("eigenvalues_parallel_analysis.csv"); load = t("table09_exploratory_pca_loadings.csv")
    lgd = s("logistic_partial_shift_diag.csv").iloc[0]; ov = s("regression_overlap_diagnostics.csv").iloc[0]
    m1 = reg[(reg.model.str.startswith("M1 PPM")) & (reg.term != "const")]; d1 = dg.iloc[0]
    nreg = s("analysis_n_register.csv"); tri = pd.read_csv(C.SEC / "triangulation_matrix.csv"); crm = t("table19_crm_recommendations.csv")
    seg = t("table15_segment_findings_current_users.csv"); grp = s("group_by_profile_tests.csv")
    fu = s("former_summary.csv").iloc[0]; h10 = s("hypothesis_test_H10.csv").iloc[0]; h9 = s("hypothesis_test_H9.csv").iloc[0]
    lit = pd.read_csv(C.LIT / "references.csv"); src = pd.read_csv(C.SEC / "sources.csv")
    fmain = t("table13_former_main_reason.csv"); fall = t("table13b_former_all_reasons_multiselect.csv"); dest = t("table14_switching_destination.csv")
    ipsat = t("table21_within_person_centering_sensitivity.csv"); htmt = t("table22_discriminant_validity_htmt.csv"); h5 = t("table20_h5_item_diagnostics.csv"); h5x = s("h5_additional_diagnostics.csv").iloc[0]
    ver = s("verification_log.csv"); ret = t("table13c_former_return.csv"); alt = t("table13c_former_alt_variants.csv"); inc = t("table13c_former_increased_other.csv")
    ds = t("table10_descriptive_statistics_current.csv").set_index("variable"); vol = t("table13e_voluntary_only_main_reason.csv")
    nvr = t("table16b_never_reason.csv")
    kmo_v = float(kmo.kmo); pc1 = float(eig.eigenvalue.iloc[0])
    media = pd.read_csv(C.SEC / "media_claims_register.csv"); litev = pd.read_csv(C.LIT / "hypothesis_evidence.csv")
    nA = int((lit.verification_level == 'A').sum()); nB = int((lit.verification_level == 'B').sum()); nC_ = int((lit.verification_level == 'C').sum()); nU = int((lit.verification_level == 'UNVERIFIED').sum())
    hh = h.set_index("construct")
    A = int(fu.n_area_primary); nB = int(fu.n_class_B); nC = int(fu.n_class_C)
    R = f"""# Investigating the Factors Influencing Customer Switching Behaviour in India's Quick-Commerce Industry: An Empirical Study of Zepto

*Revised after quality-control audit. Generated by `run_analysis.py`; every number below is read from result files. Cross-sectional, non-probability sample: all findings are associations, not causes. Questionnaire versions: V1 = responses 1-16, V1.5 = 17-22, V2 = 23-184.*

## 1. Executive summary

**Sample.** 184 responses: 51 current, 73 former and 60 never-users of Zepto. Every analysis reports its own n (current-user analyses n = 51, or 46 where V1 respondents lack an item; former users n = 73 or 68).

**Former users (behavioural, n = 73).** The most common single main reason for leaving was that Zepto was not available in the respondent's area ({A}/73, {fmain.pct.iloc[0]:.1f}%, 95% CI {fmain.ci_low.iloc[0]:.0f}-{fmain.ci_high.iloc[0]:.0f}%). This is a coverage constraint, not a clear platform choice, and the wording may also capture local availability. Among the {nC} former users with no coverage element, product availability and product variety each account for 8 main reasons (16/{nC} together), with wide intervals.

**Current users (intention, n = 51).** On raw scores, perceived alternative attractiveness, competitor variety and competitor promotions were strongly associated with switching intention (rho about 0.69-0.70, Holm p < .001). **These results are fragile:** the pull items overlap conceptually with the intention items, the constructs are not empirically distinct (HTMT above .85 for several pairs), and the associations shrink to near zero for alternative attractiveness (rho = {ipsat.set_index('construct').loc['ALT','rho_within_person_centered']:+.2f}) after a within-person centering sensitivity check. Satisfaction, familiarity and inertia were not significantly associated with intention (inconclusive). Perceived switching effort was strongly associated with intention in the **opposite** direction to the hypothesis (rho = {hh.loc['SWEFFORT','spearman_rho']:+.2f}); this is treated as an **anomalous, uninterpretable** result (Section 21).

**Regression.** The exploratory model (n = 51) has R² = {d1.r2:.2f}, but the pull composite alone gives R² = {ov.R2_PULL_alone:.2f} and its items overlap with the outcome. It is **not** evidence that distinct PPM factors explain about 70% of switching behaviour.

**Intention versus behaviour.** Intention did not differ between current users who had and had not shifted some purchases (n = {int(h9.n1+h9.n2)}, p = {h9.p:.2f}); coverage-driven and voluntary former users did not differ significantly in willingness to return (n = {int(h10.n1+h10.n2)}, p = {h10.p:.2f}).

**Secondary evidence (limited).** The SEBI-hosted Draft Abridged Prospectus of 8 June 2026 was read in full, and the UDRHP-I front matter and definitions (pp. 1-16) were read. The UDRHP-I Risk Factors, Industry Overview, Business and MD&A sections could not be read (the sandbox cannot download from sebi.gov.in and the fetch tool returns only the opening of the PDF). A few short UDRHP-I passages (e.g., the competition risk text) were retrieved only as search-index excerpts without page numbers (S11), so the Zepto organizational research is **not comprehensive**. Redseer public articles S03-S05 were read in full; the commissioned Redseer report was not opened. Media-reported filing claims are listed separately and are not evidence (Section 26).

## 2. Introduction and 3. Organizational background
Zepto is an Indian quick-commerce platform. Verified from the Draft Abridged Prospectus (S09): 47.97 million annual transacting users and 1,139 dark stores at 31 March 2026 (pp. 2-3); trailing-12-month ATU was 49.54 million at 31 December 2025 and 47.97 million at 31 March 2026 while orders per day rose from 1.81 to 2.33 million (p. 11); proceeds are earmarked for dark-store expansion in existing and new geographies (p. 5). Page numbers are derived from printed markers in the extracted text and may be off by one.

## 4-6. Problem, research question, objectives
Unchanged from the approved title. Question: which factors are associated with customer switching behaviour among Zepto users? Objective 1: identify push, pull and mooring factors. Objective 2: examine their associations empirically and propose CRM actions.

## 7. Literature review (verification levels A = full text read, B = abstract/database record, C = bibliographic only)
{_md(lit[['id','authors','year','title','doi','verification_level','use_status','sample_size']].assign(title=lambda d: d.title.str[:60], doi=lambda d: d.doi.str[:32], use_status=lambda d: d.use_status.str[:60]))}
Verification counts: A (full text) = {nA}; B (abstract/database record) = {nB}; C (bibliographic only) = {nC_}; UNVERIFIED (not usable as evidence) = {nU}. A/B/C labels are not upgraded without opening the paper. Statements drawn from B/C sources are limited to what their abstracts or bibliographic entries state.
**Key verified points (full text, label A).** L05 (n = 441, Taiwan, platform-to-platform): attractive alternatives predicted switching intention (path 0.328); satisfaction did not (0.071); its "mooring" construct was subjective norms (-0.405), not switching cost. L10 (n = 252, Jakarta, physical market to e-grocery app): attractiveness 0.314 (p = .015), dissatisfaction 0.127 (p = .069, not supported), switching cost +0.294 (p = .017, positive) with items about the effort of changing to the alternative. L06 (abstract) reports a non-significant switching-cost effect. The switching-cost literature retrieved is therefore **mixed**, and no verified study showing the hypothesised negative direct effect was retrieved. L07 and L09 are UNVERIFIED (authors/venue unconfirmed) and were withdrawn from hypothesis support.

**Literature evidence class per hypothesis** (`literature/hypothesis_evidence.csv`):
{_md(litev, ['H','relation','evidence_class','note'])}

## 8. Research gap (restricted claim)
In the non-systematic search conducted, no directly verified quick-commerce-specific PPM switching study was identified. Retrievable Indian quick-commerce studies were mostly small descriptive surveys in outlets whose indexing could not be verified (excluded: `literature/excluded_candidates.csv`). This is not proof that none exists. What the present data can add is limited to: (a) a small Zepto-specific sample combining current-user intention with former-user reasons, (b) separation of coverage-driven exits from voluntary exits, and (c) evidence on how well a PPM measurement structure holds in a small sample.

## 9-10. Theoretical, measured and supported: three distinct layers
| Layer | Content |
|---|---|
| Theoretical PPM framework | Push (dissatisfaction), pull (alternative attractiveness), mooring (switching costs, habit/inertia) |
| Empirically measured constructs | SAT (2 items), ALT (2), VAR (2; 1 for V1), PROMO (1), SWEFFORT (2), FAM (1), INERT (1; n = 46), INT (3). Not measured as Likert items: price, app experience, service, delivery, product availability |
| Statistically supported relationships | On raw scores: ALT, VAR, PROMO with intention (fragile). Anomalous: SWEFFORT. Inconclusive: SAT, FAM, INERT. No PPM structural model is supported |

**Discriminant validity is not established.** HTMT (n = {int(htmt.n.iloc[0])}): ALT-VAR = {htmt.set_index('pair').loc['ALT - VAR','HTMT']:.2f}, ALT-INT = {htmt.set_index('pair').loc['ALT - INT','HTMT']:.2f}, VAR-INT = {htmt.set_index('pair').loc['VAR - INT','HTMT']:.2f}, SWEFFORT-INT = {htmt.set_index('pair').loc['SWEFFORT - INT','HTMT']:.2f} (values >= .85 indicate constructs cannot be distinguished). Exploratory PCA: KMO = {kmo_v:.2f}, Bartlett p < .001, parallel analysis retains one component (eigenvalue {pc1:.2f}, {100*pc1/13:.0f}% of variance, 13 items, n = 51, ratio 1:{51/13:.1f}). For comparison, L05 reported distinct constructs with AA-SI correlation .454, so the present data show much stronger overlap, consistent with a common response tendency, but this cannot be proven. Figure 8 shows the conceptual model.
{_md(htmt, ['pair','n','HTMT','ci_low','ci_high','verdict'])}

## 11. Hypotheses
Defined in `src/config.py` and frozen in `documentation/hypothesis_registry.json` (SHA-256 recorded) at the start of each run, before any test executes. They were written after the Phase-1 audit, in which item-level descriptive correlations had been shown, so they were theory-led but not blind to those descriptives (H5 was kept as negative despite the audit showing positive item correlations). They were not changed after inferential results. Decision rule: Supported iff direction as hypothesised and Holm-adjusted p < .05 within H1-H7.
{_md(hm, ['H','Construct','Expected_direction','n','Coefficient','CI95','p_Holm','Evidence_label','Literature_evidence_class'], floatfmt=3)}
**Full matrix (rationale, literature, items, planned test, robustness):** `documentation/hypothesis_matrix.xlsx`.

## 12. Methodology
Spearman correlations (bootstrap 95% CI, 5,000 resamples, seed {C.SEED}); OLS with HC3 SEs and bootstrap CIs; Mann-Whitney; permutation chi-square; Wilson intervals; Holm correction within declared families. **Not used:** SEM/PLS-SEM (n = 51, single-item constructs, one dominant component); machine learning (no validated binary outcome; 29 vs 22 cases); EFA for construct building (ratio 1:{51/13:.1f}).

## 13-14. Population, sampling, questionnaire
Convenience sample collected 21 Aug to 23 Sep 2026 in three questionnaire versions: V1 (responses 1-16), V1.5 (17-22), V2 (23-184). Boundaries were inferred from timestamps and item availability; the CSV cannot show wording changes. Items absent in V1 (VAR2, INERT1, fu_alt_variants, fu_return, location, spend) are structural missingness.

## 15. Data cleaning
No response excluded. Routing-leak reconciliation: **15 unique respondents** answered out-of-branch blocks (7 current users answered both the former-user and never-user blocks; 8 former users answered the never-user block). Block-level incidents = 7 + 15 = 22; the earlier "22 leaks" double-counted the 7 current users and coincides with the size of V1+V1.5 (22) by chance. All 15 are among responses 2-22. Other flags: 12 straight-liners (6 all-4, 4 all-5, 2 all-3), 40 Q1 inconsistencies (Zepto tick inconsistent with group), structural missingness. See `documentation/cleaning_log.xlsx`.
{_md(t('table04_data_cleaning_summary.csv'))}

## 16-17. Respondent profile and descriptives
157/184 respondents are aged 18-24 and 149/184 are students, so profile findings do not generalise beyond young student users. Group composition differs by occupation, spend and frequency (permutation chi-square, Holm p = {', '.join(f'{v:.3f}' for v in grp.p_perm_holm.iloc[[1,3,4]])}; Cramér's V about 0.24-0.25; 27-50% of cells have expected counts below 5).
{_md(t('table10_descriptive_statistics_current.csv'), ['variable','n','mean','sd','ci95_low','ci95_high','median','pct_agree'])}

## 18. Reliability
{_md(rel, ['scale','n_items','n_complete','alpha','mean_inter_item_r','spearman_brown'], floatfmt=3)}
FAM1 and INERT1 were not pooled (alpha 0.50). No items deleted. High alpha for INT (about .91) combined with strong cross-construct overlap should not be read as validity.

## 19. Validity and factor analysis
See Sections 9-10. The exploratory component loadings are in Table 9; SAT1, SAT2 and FAM1 load weakly while pull, effort and intention items load together.

## 20. Hypothesis testing (H1-H7)
Supported on raw scores: H2, H3, H4. Inconclusive: H1, H6, H7 (CIs include zero and moderate effects; minimum detectable |rho| about 0.38 at n = 51, 0.40 at n = 46). Anomalous: H5. Robustness to within-person centering (exploratory; centering can itself induce artefacts):
{_md(ipsat, ['construct','n','rho_raw','rho_within_person_centered','ci_low_centered','ci_high_centered'], floatfmt=2)}
So H2-H4 rest on between-person differences in overall agreement plus content; they should be treated as tentative.

## 21. H5 / switching effort: investigation
Coding was checked: SC1 and SC2 are both keyed so that agreement means higher perceived effort, no reverse-coding is needed, and the composite is the simple mean; the raw CSV values match (verification log).
{_md(h5, ['variable','description','n','spearman_rho','ci_boot_low','ci_boot_high','p','matches_expected'], floatfmt=3)}
Findings: (1) All four retention-keyed constructs (SAT, SWEFFORT, FAM, INERT) correlate positively with intention (expected negative); only SWEFFORT is significant. (2) SC2 states that effort makes the respondent *less* likely to switch, yet {int(h5x['SC2_agree_and_INT_ge_3.5_n'])}/{int(h5x['SC2_agree_n'])} ({h5x['SC2_agree_and_INT_ge_3.5_pct']:.0f}%) of those agreeing also report high switching intention; taken at face value these answers are contradictory. (3) The association persists without straight-liners (rho = {h5x['rho_SWEFFORT_INT_excl_straightliners']:.2f}, n = {int(h5x['n_excl_straightliners'])}) and in V2 only (rho = {h5x['rho_SWEFFORT_INT_V2_only']:.2f}, n = {int(h5x['n_V2_only'])}), and after controlling for PULL and SAT (partial rho = {h5x['partial_rho_SWEFFORT_INT_given_PULL_SAT']:.2f}), so it is not an artefact of straight-liners or of pull. (4) Within-person centering removes it (rho about +0.05) and HTMT with intention is {htmt.set_index('pair').loc['SWEFFORT - INT','HTMT']:.2f}. **Interpretation:** a coding error is not found; a measurement/response-style problem is plausible but cannot be confirmed with this data. Substantive explanations (respondents who consider switching have thought about the effort) are untested. A verified full-text study (L10) also reported a positive switching-cost coefficient with items about the effort of changing to the alternative, but it concerns channel adoption and does not explain the present result. The result is labelled **anomalous / inconclusive** and is not evidence that effort promotes switching.

## 22. Regression (exploratory, associational)
Model M1 (SAT, PULL, SWEFFORT, FAM; n = {int(d1.n)}, {d1.cases_per_predictor:.1f} cases/predictor): R² = {d1.r2:.2f}, adjusted R² = {d1.adj_r2:.2f}, F p < .001, max VIF = {d1.max_vif:.2f}, residual Shapiro p = {d1.shapiro_resid_p:.3f} (non-normal, so HC3 and bootstrap intervals), Breusch-Pagan p = {d1.breusch_pagan_p:.2f}. PULL alone gives R² = {ov.R2_PULL_alone:.2f}; adding SAT, SWEFFORT and FAM adds {ov.R2_gain_from_SAT_SWEFFORT_FAM:.2f}. Pooling the four pull items with the three intention items gives alpha = {ov.alpha_pull4_plus_intention3_pooled:.2f} (n = {int(ov.n_pooled)}), showing they behave as one scale. The SWEFFORT coefficient inherits the H5 anomaly.
{_md(m1, ['term','n','b','se_hc3','p_hc3','ci_boot_low','ci_boot_high','std_beta'], floatfmt=3)}
Sensitivity (n = 33-51): PULL stays significant in all five samples; SWEFFORT in four (p_HC3 = 0.053 when Q1-inconsistent respondents are excluded); SAT and FAM never.
{_md(sens, ['sample','n','term','b','p_hc3','r2'], floatfmt=3)}
Logistic model for partial shifting (n = {int(lgd.n)}, {int(lgd.events)} events; 3 predictors): no significant term, LR p = {lgd.LR_p:.2f}. V1/V1.5 current users (n = 7) did not differ from V2 (n = 44) on shared constructs (all p > .30).

## 23. Former users (n = 73; return items n = 68)
{_md(fmain, ['category','n','pct','ci_low','ci_high'], floatfmt=1)}
Any-mention frequencies: {'; '.join(f"{r.reason} {int(r.n_mentions)}/73" for r in fall.head(5).itertuples())}. Destination: {dest.category.iloc[0]} {int(dest.n.iloc[0])}/73.
**Coverage vs voluntary.** Class A (area is main reason) = {A}; class B (area mentioned, other main reason) = {nB}; class C (voluntary only) = {nC}. Three respondents chose "Availability in my area" without ticking the area option in Q21. Return willingness: class A mean 3.79 (n = 28), class C mean 3.47 (n = 30); H10 not supported (p = {h10.p:.2f}). Interpretation: coverage-driven exit is a service-availability constraint and is **not classified as PPM push or pull**; pooling it with voluntary switching would overstate platform-choice switching. **Limitation:** "Availability in my area" could reflect geographic service coverage or local product availability; the Q21 wording "Zepto was not available in my area" is clearer (38/73 ticked it).
Leaked out-of-branch answers of 7 current users (Table 13g) are reported separately as supplementary behavioural evidence and not pooled.

## 24. Never-users (context only, n = 60)
Main reason for never using Zepto: {nvr.category.iloc[0]} ({int(nvr.n.iloc[0])}/60). Never-users are not used in any switching-away analysis.

## 25. Profile and segmentation (current users; cautious)
No segment difference in intention (age, student status, location, spend, frequency; all Holm p >= 0.46; n = 46-51). Cells are tiny and the sample is 85% aged 18-24 and 81% students, so these are null results with little power.
{_md(seg, ['comparison','n1','n2','p','p_holm_5tests'], floatfmt=3)}

## 26. Secondary-data analysis
**Zepto (primary filing evidence; Draft Abridged Prospectus page numbers derived from printed page markers, +/-1):**
{_md(pd.read_csv(C.TABLES / 'table16_zepto_secondary_evidence.csv'), ['source','page','claim','claim_owner','evidence_type','relation_to_survey'])}
Zepto identifies these items as business risks or strategies; the filing text does not show, and this report does not claim, that any of them causes customer switching.\n
**Industry evidence:**
{_md(pd.read_csv(C.TABLES / 'table17_industry_secondary_evidence.csv'), ['source','claim','evidence_type','use'])}
**Media-reported claims (NOT evidence; checked against the primary filing):**
{_md(media, ['id','media_source','claim','status'])}
**Coverage limit (S01).** {src.set_index('id').loc['S01','coverage_limit']}
**Commissioned Redseer report (S02).** {src.set_index('id').loc['S02','verification']}

## 27. Triangulation
{_md(tri, ['Factor','Academic','Zepto_evidence','Industry_evidence','Current_users','Former_users','Statistical','Classification'])}
Evidence types are kept apart: survey descriptives, inferential tests, organizational (filing) evidence, industry evidence, academic evidence, interpretation. Zepto's disclosed risks are not treated as proven causes.

## 28. Discussion
Coverage is the largest stated exit reason among former users. Among voluntary leavers, product availability and variety are the most frequent named reasons but are few in number. Current-user perceptions of competitor appeal co-vary with intention on raw scores, but measurement limits prevent a firm conclusion about which pull facet matters. The study does not establish product availability as the main cause of switching.

## 29-31. CRM implications and recommendations
{_md(crm, ['ID','Status','Problem','Evidence','Segment','Mechanism','Implementation','Expected','KPI'])}
Recommendations are evidence-based proposals to be piloted with control groups, not predictions.

## 32. Research contribution (bounded)
This study contributes (i) descriptive Zepto-specific evidence in an Indian quick-commerce sample, (ii) current-user switching-intention associations with explicit measurement caveats, (iii) former-user behavioural reasons with a distinction between coverage-driven and voluntary exit, and (iv) transparent evidence that a PPM structure was not empirically distinguishable in a small sample. It does not prove causes of switching and makes no claim of novelty beyond the limited search reported in Section 8.

## 33. Limitations
Convenience sample (85% aged 18-24, 81% students); n = 51 current users; single-item constructs; item overlap between pull and intention; probable response-style effects; cross-sectional self-reports; three questionnaire versions with routing leaks; Q1 inconsistencies; only L05 and L10 read in full; UDRHP-I risk sections not read; Redseer commissioned report not opened; page numbers for the abridged prospectus approximate.

## 34. Future research
Validated, reverse-worded switching-cost and satisfaction scales; separate measures of price, app, delivery and product availability; probability sampling; transactional data for actual switching; verify the UDRHP Risk Factors pp. 23-63.

## 35. Conclusion
Within these limits: coverage limits explain the largest share of former-user exits; competitor-related perceptions co-vary with switching intention on raw scores but are not statistically distinct; satisfaction, familiarity and inertia are inconclusive; switching effort is anomalous. No causal claim is made.

## 36. References (verified records; see `literature/references.csv` for verification level)
{chr(10).join(f"- {r.id}: {r.authors} ({r.year}). {r.title}. {r.venue}. DOI: {r.doi}. [Verification: {r.verification_level}; {r.use_status}]" for r in lit.itertuples())}

## 37. Appendices
**A. Independent verification.** {int(ver.passed.sum())}/{len(ver)} checks recomputing counts, correlations, Holm p-values, alphas, OLS coefficients, subgroup tests and former-user classes directly from the raw CSV passed (`outputs/statistical_results/verification_log.csv`).
**B. n register.**
{_md(nreg)}
"""
    (C.REPORTS / "final_report.md").write_text(R, encoding="utf-8")
    M = f"""# Methodology notes
1. Raw data `data/raw/Quick-Commerce_Survey.csv` is never modified. Groups from Q4 (current, former, never). Never-users are excluded from switching-away analyses.
2. Questionnaire versions: V1 = responses 1-16, V1.5 = 17-22, V2 = 23-184. Items added later are structural missingness (NaN, never zero).
3. Routing leaks: 15 unique respondents (22 block-level incidents), flagged, removed from primary datasets, reported as supplementary.
4. Straight-lining is ambiguous on a mixed-polarity item set; respondents retained; sensitivity analyses with/without.
5. Hypotheses frozen in `src/config.py` and hashed in `documentation/hypothesis_registry.json` at the start of each run; decision rule Holm p < .05 with correct direction; labels Supported / Inconclusive / Anomalous.
6. Regression is exploratory/associational; R2 is inflated by item overlap (see `regression_overlap_diagnostics.csv`).
7. Measurement diagnostics: HTMT, within-person centering, H5 item diagnostics.
8. Independent verification recomputes key results from the raw CSV (`src/verification.py`); consistency checks in `src/consistency_check.py`.
9. Secondary evidence: only retrieved sources recorded; verification levels and coverage limits stated in `secondary_data/sources.csv`.
10. Random seed: {C.SEED}.
11. Source IDs: S01 (UDRHP-I), S09 (Draft Abridged Prospectus), S02 (commissioned Redseer report, not opened), S03-S05 (public Redseer articles, read in full). S06, S07, S10 are media sources kept in `secondary_data/media_sources_not_evidence.csv` / `media_claims_register.csv` (M01-M08). S08 was retired (an earlier generic media-summary entry, superseded by the media-claims register); the gap is intentional.
12. Literature/source lists are curated in `src/secondary_analysis.py` (source of truth); triangulation, hypothesis matrix and CRM logic are in `src/synthesis.py`. Edit those files and re-run `run_analysis.py`; do not edit generated CSVs.
"""
    (C.DOCS / "methodology_notes.md").write_text(M, encoding="utf-8")
    README = """# Zepto switching-behaviour analysis (reproducible pipeline)

## Run in VS Code
1. Install Python 3.10+ and open this folder in VS Code.
2. Terminal: `python -m venv .venv`, then activate it (Windows: `.venv\\Scripts\\activate`; macOS/Linux: `source .venv/bin/activate`).
3. `pip install -r requirements.txt`
4. `python run_analysis.py`

The run ends with an independent verification step (recomputes key results from the raw CSV) and a consistency check; it stops with an error if either fails.

Outputs: `outputs/tables`, `outputs/figures`, `outputs/statistical_results`, `outputs/reports/final_report.md`, `documentation/*`, `data/cleaned`, `data/processed`, `secondary_data`, `literature`.

The raw CSV in `data/raw` is never modified. Literature and secondary-source files are curated records of what was actually retrieved (with verification levels), not regenerated from the web.
"""
    (C.ROOT / "README.md").write_text(README, encoding="utf-8")
