"""SOURCE OF TRUTH for the curated literature database, secondary-source list, primary/industry evidence items,
media-claims register and statistics register. Edit this file (not the generated CSVs) and re-run run_analysis.py.

Verification labels (used consistently):
  A = full text checked        B = abstract/database/publisher record checked
  C = bibliographic entry only UNVERIFIED = must not be used as evidence
Nothing here was filled from memory; fields not verified say 'not verified'.
"""
import pandas as pd
from . import config as C

NV = "not verified"

LITERATURE = [
    dict(id="L01", authors="Bansal, H.S.; Taylor, S.F.; St. James, Y.", year=2005,
         title="'Migrating' to new service providers: Toward a unifying framework of consumers' switching behaviors",
         venue="Journal of the Academy of Marketing Science 33(1), 96-115", doi="10.1177/0092070304267928",
         verification_level="B", use_status="Used (theory; abstract-level empirical)",
         source_location="ProQuest abstract record; DOI and citation also read in the reference list of L10 (full text)",
         hypothesis_supported="Framework for H1-H7 (generic)",
         verification="Abstract record retrieved; DOI confirmed in L10's reference list; full text not read", context=NV, sample_size="approx. 700 consumers (per abstract)",
         method="Survey; PPM compared with an alternative model", constructs="Push, pull, mooring", measurement=NV,
         key_findings="Per abstract: PPM outperformed an alternative model; push, pull and mooring variables had significant direct effects and some moderating effects on switching intentions",
         relevance="Theoretical basis of PPM", role="foundational"),
    dict(id="L02", authors="Moon, B.", year=1995, title="Paradigms in migration research: Exploring 'mooring' as a schema",
         venue="Progress in Human Geography 19(4), 504-524", doi="10.1177/030913259501900404", verification_level="C", use_status="Background only (theory attribution)",
         source_location="Reference list of L10 (full text) incl. DOI; L10 Section 2.1 describes Moon as adding 'mooring' to push-pull migration", hypothesis_supported="none (attribution of mooring concept)",
         verification="Bibliographic entry and DOI read in L10's reference list; paper not opened", context="Human geography", sample_size="n/a (conceptual)", method="Conceptual", constructs="Mooring",
         measurement="n/a", key_findings="Not extracted", relevance="Origin of the mooring concept", role="foundational"),
    dict(id="L03", authors="Hsieh, J.-K.; Hsieh, Y.-C.; Chiu, H.-C.; Feng, Y.-C.", year=2012, title="Post-adoption switching behavior for online service substitutes: A perspective of the push-pull-mooring framework",
         venue="Computers in Human Behavior 28(5), 1912-1920", doi="10.1016/j.chb.2012.05.010", verification_level="C", use_status="Background only (not used for any hypothesis)",
         source_location="Seen in a retrieved bibliography only", hypothesis_supported="none", verification="Bibliographic entry only; paper not opened", context=NV, sample_size=NV, method=NV, constructs="PPM",
         measurement=NV, key_findings="Not extracted", relevance="None beyond background", role="background"),
    dict(id="L04", authors="Burnham, T.A.; Frels, J.K.; Mahajan, V.", year=2003, title="Consumer switching costs: A typology, antecedents, and consequences",
         venue="Journal of the Academy of Marketing Science 31(2), 109-126", doi=NV, verification_level="C", use_status="Background only (theory attribution)",
         source_location="Seen in two retrieved bibliographies", hypothesis_supported="H5 (theoretical rationale only)", verification="Bibliographic entry only; DOI not retrieved; paper not opened", context=NV, sample_size=NV, method=NV,
         constructs="Switching-cost typology", measurement=NV, key_findings="Not extracted", relevance="Theoretical origin of the switching-cost concept; no empirical claim drawn", role="foundational"),
    dict(id="L05", authors="Chang, I.-C.; Shiau, W.-M.; Lin, C.-Y.; Shih, D.-H.", year=2023,
         title="Consumer Intentions to Switch On-Demand Food Delivery Platforms: A Perspective from Push-Pull-Mooring Theory",
         venue="Journal of Theoretical and Applied Electronic Commerce Research 18(4), 2217-2232", doi="10.3390/jtaer18040111", verification_level="A", use_status="Used",
         source_location="Open-access MDPI full text: Methods (measures and appendix items), Results (structural-model paths), Discussion; table numbers not recorded",
         hypothesis_supported="H1 (contrary: satisfaction n.s.), H2 (supports), H3/H4 (indirect: attractiveness scale content), H8",
         verification="Full text read", context="Taiwan; on-demand food delivery platforms (platform-to-platform)", sample_size="441 usable responses (self-selected online)", method="Survey; PLS-SEM; Fornell-Larcker",
         constructs="Push = satisfaction; pull = attractive alternatives; mooring = subjective norms",
         measurement="5-point Likert; attractive alternatives 5 items (one on deals/promotions); switching intention 3 items incl. 'intend to reduce the use of [platform]'; alpha SI .674, SN .619",
         key_findings="Attractive alternatives -> switching intention 0.328 (significant); satisfaction -> switching intention 0.071 (not significant); subjective norms -> switching intention -0.405 (significant, negative); about 42% variance explained; construct correlation AA-SI .454; mean satisfaction 3.89",
         relevance="Closest verified platform-to-platform analogue; its 'mooring' is subjective norms, NOT switching cost", role="recent"),
    dict(id="L06", authors="Guan, Z.; Shi, X.; Ying, H.; Xue, R.; Qiao, X.", year=2024,
         title="An empirical study on traditional offline retailer's switching intention towards community-based group buying program: A push-pull-mooring model",
         venue="Electronic Markets 34(1), article 18", doi="10.1007/s12525-024-00702-6", verification_level="B", use_status="Used with caution (abstract-level)",
         source_location="Springer abstract page; RePEc record; x-mol listing (authors, DOI, publication date 29 Feb 2024)", hypothesis_supported="H1/H2 (push and pull positive, abstract), H5 (switching cost n.s., abstract)",
         verification="Publisher abstract and RePEc record read; full text not read", context="Community group buying; respondents are retailers (not consumers)", sample_size="365 respondents", method="PPM + TAM; SEM",
         constructs="Push, pull, perceived risk, switching cost", measurement=NV, key_findings="Per abstract: push and pull positively related to switching intention; perceived risk hinders it; switching cost not significant",
         relevance="Recent PPM evidence; retailer context limits transfer", role="recent"),
    dict(id="L07", authors=NV, year=2023, title="Factors influencing consumers' intentions to switch to live commerce from push-pull-mooring perspective",
         venue="not verified (journal name inferred from DOI prefix only)", doi="10.4018/JGIM.319972", verification_level="UNVERIFIED", use_status="Do NOT cite as evidence until authors/venue/year are confirmed on a publisher page",
         source_location="Aggregator abstract page only", hypothesis_supported="none (previously used for H6/H7; withdrawn)", verification="Authors, venue and year not confirmed", context="China (per abstract)", sample_size="306 consumers (per abstract; unconfirmed)",
         method="PPM survey", constructs="PPM; inertia/habit", measurement=NV, key_findings="Not used", relevance="Withdrawn from evidence base", role="unverified"),
    dict(id="L08", authors="Cui, Y.; Yao, X.; Zhao, D.; Li, J.", year=2026,
         title="The influence of information processing on consumer switching intention from traditional to short video e-commerce: a structural equation modelling study",
         venue="Asia Pacific Journal of Marketing and Logistics", doi="10.1108/APJML-01-2025-0001", verification_level="B", use_status="Used with caution (abstract-level)",
         source_location="Emerald abstract page excerpt", hypothesis_supported="H7 (inertia as moderator; abstract only)", verification="Publisher abstract excerpt read; full text not read", context=NV, sample_size=NV, method="Survey; SEM; PPM",
         constructs="Overload confusion, virtual touch, vicarious learning, online consumer inertia", measurement=NV, key_findings="Per abstract: online consumer inertia moderates paths to switching intention", relevance="Inertia as moderator; not a direct-effect test", role="recent"),
    dict(id="L09", authors=NV, year=2025, title="Research on consumers' fresh food e-commerce platform switching intention under PPM theory: A fsQCA method",
         venue="WHICEB 2025 (Springer chapter)", doi=NV, verification_level="UNVERIFIED", use_status="Do NOT cite as evidence until authors are confirmed on the publisher page",
         source_location="Springer chapter abstract; authors/DOI not captured", hypothesis_supported="none (previously cited for H3; withdrawn)", verification="Authors not confirmed", context="Fresh-food e-commerce", sample_size=NV, method="fsQCA",
         constructs="PPM", measurement=NV, key_findings="Not used", relevance="Withdrawn from evidence base", role="unverified"),
    dict(id="L10", authors="Monoarfa, T.A.; Sumarwan, U.; Suroso, A.I.; Wulandari, R.", year=2023,
         title="Switch or Stay? Applying a Push-Pull-Mooring Framework to Evaluate Behavior in E-Grocery Shopping",
         venue="Sustainability 15(7), 6018", doi="10.3390/su15076018", verification_level="A", use_status="Used",
         source_location="Open-access MDPI full text: Section 3.1-3.2 (sampling, instrument), Table 2 (alphas), Table 3 (direct paths), Table 4 (moderation), Appendix A Table A1 (items)",
         hypothesis_supported="H1 (dissatisfaction n.s.), H2 (attractiveness significant), H5 (switching cost POSITIVE sign; contrary to hypothesised direction)",
         verification="Full text read", context="Jakarta, Indonesia; switching from physical markets TO e-grocery apps (channel adoption, not platform-to-platform)", sample_size="252 analysed (265 collected); purposive/convenience, online",
         method="CB-SEM (AMOS); 39 items, 5 removed after modification indices",
         constructs="Dissatisfaction (push), alternative attractiveness (pull), switching cost (mooring), plus ease of use, usefulness, value, health consciousness, innovativeness",
         measurement="5-point Likert; switching-cost items concern the effort/learning of changing TO e-grocery (e.g. 'It would take a lot of time changing to e-grocery shopping'); alphas: DSAT .936, ATT .939, SWC .929, SWI .901",
         key_findings="Table 3: dissatisfaction -> switching intention 0.127 (p=.069, not supported); attractiveness -> switching intention 0.314 (p=.015); switching cost -> switching intention 0.294 (p=.017, positive). Table 4: switching-cost x dissatisfaction/attractiveness interactions negative",
         relevance="Verified precedent for a positive switching-cost coefficient when items describe the effort of changing to the alternative (similar wording to SC1 in the present survey); context differs from platform-to-platform switching",
         role="recent"),
    dict(id="L11", authors="Hung, P.D.; Thong, V.H.; Tuan, P.V.; Khoa, N.H.D.; Trang, N.Q.", year=2024, title="Switching intention to online channel in Vietnam - A case study of consumer electronics goods",
         venue="Cogent Business & Management 11(1), article 2291861 (received 17 Apr 2023; accepted 1 Dec 2023; online 21 Apr 2024)", doi="10.1080/23311975.2023.2291861 (taken from the publisher-hosted URL; DOI page not opened)", verification_level="B", use_status="Used with caution (abstract-level)",
         source_location="Publisher article page metadata; DOAJ and RePEc abstracts", hypothesis_supported="H6 (habit; abstract-level)", verification="Publisher metadata and abstract read; full text not read",
         context="Vietnam; switching from physical stores to online channel (consumer electronics)", sample_size="1,104 customers", method="Extended PPM; survey", constructs="Perceived risk, attitude, habit at traditional stores", measurement=NV,
         key_findings="Per abstract: habit of buying at traditional stores lessened switching intention (-0.136); attitude toward switching strongest (0.374)", relevance="Habit toward the origin channel; familiarity with Zepto is not identical", role="recent"),
    dict(id="L12", authors="Zhang, K.Z.K.; Cheung, C.M.K.; Lee, M.K.O.", year=2012, title="Online service switching behavior: The case of blog service providers",
         venue="Journal of Electronic Commerce Research 13(3), 184", doi=NV, verification_level="C", use_status="Background only",
         source_location="Reference list of L05 (full text); abstract seen on a third-party document host", hypothesis_supported="none", verification="Bibliographic entry only", context="Blog services", sample_size=NV, method="PPM survey",
         constructs="Satisfaction, attractive alternatives, sunk costs", measurement=NV, key_findings="Not extracted", relevance="Source of measurement items adapted in L05 (not independently checked)", role="background"),
    dict(id="L13", authors="Chang, I.C.; Liu, C.C.; Chen, K.", year=2014, title="The push, pull and mooring effects in virtual migration for social networking sites",
         venue="Information Systems Journal 24, 323-346", doi="10.1111/isj.12030", verification_level="C", use_status="Background only",
         source_location="Reference list of L05 (full text)", hypothesis_supported="none", verification="Bibliographic entry incl. DOI read in L05's reference list; paper not opened", context=NV, sample_size=NV, method=NV, constructs="PPM",
         measurement=NV, key_findings="Not extracted", relevance="Background", role="background"),
    dict(id="L14", authors="Celiker, O.; Ozen, U.; Bolen, M.C.", year=2024, title="Understanding Consumers' Switching Intention from e-Commerce to Social Commerce: A Mixed Methods Study",
         venue="International Journal of Innovation and Technology Management 21(1)", doi="10.1142/s0219877024500068", verification_level="B", use_status="Background only",
         source_location="University repository record", hypothesis_supported="none", verification="University repository record (Ataturk University) lists ESCI and Scopus indexing; NOT independently checked in Scopus/WoS; full text not read; the abstract states variance explained as '0.607%' (apparent typo, not used)", context="E-commerce to social commerce", sample_size=NV, method="Mixed methods; PPM",
         constructs="PPM; social influence", measurement=NV, key_findings="Per abstract: social influence moderates push and pull effects", relevance="Background", role="recent"),
    dict(id="L15", authors="Chen, L.; Wu, P.; Dou, Y.; Wu, Y.", year=2023, title="Investigating senders' switching intention to smart lockers: An extension of push-pull-mooring model",
         venue="Journal of Retailing and Consumer Services 74, article 103414", doi="10.1016/j.jretconser.2023.103414", verification_level="B", use_status="Used with caution (abstract-level)",
         source_location="RePEc/IDEAS record (abstract, DOI)", hypothesis_supported="H7 (inertia negatively affects switching intention; abstract only), H2 (attractiveness of alternative; abstract)",
         verification="RePEc abstract read; full text not read", context="Parcel delivery (senders); China per author set not verified", sample_size=NV, method="PLS-SEM; two online questionnaires (senders vs receivers)",
         constructs="Low perceived value of home pickup (push), attractiveness of smart lockers (pull), inertia (mooring)", measurement=NV,
         key_findings="Per abstract: push effect of low perceived value, pull effect of locker attractiveness, and mooring effect of inertia; inertia of using home pickup negatively affects switching intention and strengthens the push effect",
         relevance="Abstract-level direct evidence of a negative inertia effect (service-channel context, not platform-to-platform)", role="recent"),
    dict(id="L16", authors="Singh, R.; Rosengren, S.", year=2020, title="Why do online grocery shoppers switch? An empirical investigation of drivers of switching in online grocery",
         venue="Journal of Retailing and Consumer Services 53, 101962", doi="10.1016/j.jretconser.2019.101962", verification_level="B", use_status="Used with caution (abstract-level; older than the 2022-2026 window but directly relevant)",
         source_location="EconPapers and HHS repository abstract; citation and DOI also in L10's reference list (full text)", hypothesis_supported="H1 (push factors significant: customer service, product issues, technical issues, price perception), H2 (alternative attraction significant), H5 (switching cost as moderator)",
         verification="Abstract records read; full text not read", context="Online grocery retailing (country not captured)", sample_size=NV, method="PPM; empirical survey (details not captured)",
         constructs="Retailer-related push, competitor-related pull (WOM, alternative attraction), mooring (switching cost, prior switching behaviour)", measurement=NV,
         key_findings="Per abstract: push factors (customer service, delivered-product issues, technical issues, high price perception) and pull factors (WOM, alternative attraction) had significant direct effects on switching; switching cost and prior switching behaviour significantly moderated switching",
         relevance="Closest online-grocery PPM study found; supports pull and a service/product-problem push, with mooring as a moderator", role="recent"),
    dict(id="L17", authors="Haridasan, A.C.; Fernando, A.G.; Balakrishnan, S.", year=2021, title="Investigation of consumers' cross-channel switching intentions: A push-pull-mooring approach",
         venue="Journal of Consumer Behaviour (volume/pages not captured)", doi="10.1002/cb.1918", verification_level="B", use_status="Used with caution (abstract-level)",
         source_location="Publisher-linked listing with abstract (zendy.io)", hypothesis_supported="H2 (alternative attractiveness positive; abstract), H5 (lower switching costs strengthened the pull effect; moderation, abstract)",
         verification="Abstract read; full text not read", context="Cross-channel (online/offline) switching", sample_size="456 valid responses (per abstract)", method="Online and in-person survey; SEM",
         constructs="External information search (push), alternative attractiveness (pull), multichannel self-efficacy, switching costs", measurement=NV,
         key_findings="Per abstract: push and pull factors positively influenced switching intention; higher multichannel self-efficacy and lower switching costs significantly increased the pull effect",
         relevance="Switching cost enters as a moderator of the pull effect, not as a direct negative effect", role="recent"),
]

EXCLUDED_CANDIDATES = [
    dict(item="Indian quick-commerce studies surfaced by search (e.g., a 2025 satisfaction/brand-loyalty study of Blinkit and Zepto users, n=120, in IJRASET; other IJPREMS/IJRPR/IJAPT items)",
         reason="Small, descriptive; publishing outlets' indexing and peer-review standard could not be verified; papers not opened. Not used as evidence."),
    dict(item="Unverified metadata items L07 (live commerce PPM) and L09 (fresh-food fsQCA)", reason="Authors/venue not confirmed; withdrawn from hypothesis support until verified on publisher pages."),
]

SOURCES = [
    dict(id="S01", type="Primary filing (organizational evidence)", title="Zepto Limited - Updated Draft Red Herring Prospectus - I (UDRHP-I)", issuer="Zepto Limited",
         date="2026-06-08", url="https://www.sebi.gov.in/sebi_data/attachdocs/jun-2026/1780983427091.pdf",
         also_at="SEBI filing page https://www.sebi.gov.in/filings/public-issues/jun-2026/zepto-limited-udrhp1_101929.html ; BRLM copy https://www.morganstanley.com/content/dam/msdotcom/en/indiaofferdocuments/pdfs/Zepto_Limited_UDRHP-I.pdf",
         verification="Full 690-page filing read in full across all key body sections (printed pp. 1-674). Verified across Section II Risk Factors (pp. 23-63), Section III Objects of Offer (pp. 143-157), Basis for Offer Price/KPIs (pp. 158-181), Section IV Industry Overview (pp. 189-231), Our Business (pp. 232-276), and Section V MD&A (pp. 529-575).",
         coverage_limit="Covers all disclosed operational, KPI, risk, and financial parameters in the filing. Filing figures represent company-reported disclosures and KPIs, not econometric causal tests of consumer switching motivations.",
         version_note="Latest version: UDRHP-I, 8 June 2026."),
    dict(id="S09", type="Primary filing (organizational evidence)", title="Zepto Limited - Draft Abridged Prospectus (salient features of UDRHP-I)", issuer="Zepto Limited; hosted by SEBI",
         date="2026-06-08", url="https://www.sebi.gov.in/sebi_data/commondocs/jun-2026/Zepto%20Limited%20-%20abridged_p.pdf", also_at="",
         verification="Full text read (19 printed pages). Cross-checked against UDRHP-I master filing.",
         coverage_limit="Summary document; references inside correspond to UDRHP-I printed pages.", version_note="Abridged companion to S01."),
    dict(id="S02", type="Industry report (commissioned by Zepto)", title="India's Quick-Commerce Industry: Market Structure and Growth Drivers", issuer="Redseer Strategy Consultants (commissioned and paid for by Zepto)",
         date="2026-05-30", url="listed as 'Industry Report' on https://investors.zepto.com/results/", also_at="",
         verification="Existence, title, date and commissioning confirmed from UDRHP-I p.3 and p.194. The standalone report file was NOT retrieved independently; figures from it are quoted from the primary UDRHP-I text and labelled company-cited/commissioned.",
         coverage_limit="Report content accessed as reproduced within UDRHP-I", version_note="Exclusively commissioned by Zepto."),
    dict(id="S03", type="Industry article (independent Redseer publication)", title="Quick Commerce Finds Its New Normal with Scale, Mix, and Momentum", issuer="Redseer (author: Nikhil Dalal)", date="2026-02-12 (page modified 2026-02-23)",
         url="https://redseer.com/articles/quick-commerce-finds-its-new-normal-with-scale-mix-and-momentum/", also_at="", verification="Full article text read", coverage_limit="Figures derived from Redseer's proprietary 'Benchmarks' platform; underlying data not inspected", version_note=""),
    dict(id="S04", type="Industry article (independent Redseer publication)", title="Scaling Quick Commerce Beyond Metros: A Strategic Reassessment", issuer="Redseer (author: Kushal Bhatnagar)", date="2025-07-03 (page modified 2025-11-06)",
         url="https://redseer.com/articles/scaling-quick-commerce-beyond-metros-a-strategic-reassessment/", also_at="", verification="Full article text read", coverage_limit="Opinion/analysis article", version_note=""),
    dict(id="S05", type="Industry article (independent Redseer publication)", title="Quick Commerce, Quicker Decisions: Is your Brand Strategy Future-ready?", issuer="Redseer (author: Kushal Bhatnagar)", date="2025-11-19 (page modified 2026-01-22)",
         url="https://redseer.com/articles/quick-commerce-quicker-decisions-is-your-brand-strategy-future-ready/", also_at="", verification="Full article text read", coverage_limit="Brand-strategy article; mentions Zepto Atom only as a brand analytics tool", version_note=""),
    dict(id="S11", type="Primary filing (organizational evidence) - excerpt level", title="Zepto Limited - UDRHP-I (Zepto investor-site copy), passages returned by a search index", issuer="Zepto Limited",
         date="2026-06-08", url="https://cdn.zeptonow.com/investors/documents/Zepto%20Limited%20-%20UDRHP-I.pdf", also_at="same text as S01",
         verification="Historical search-index excerpts; superseded by full-text reading of S01.",
         coverage_limit="Search engine excerpt selection; superseded by S01.", version_note="Same document as S01"),
]

MEDIA_SOURCES = [
    dict(id="S06", title="Zepto's Battle Beyond Speed", issuer="Inc42", date="2026-06-14", url="https://inc42.com/features/zeptos-battle-beyond-speed/"),
    dict(id="S07", title="Zepto's Retention Play: Fewer Discounts, Premium Carts & A Paid Club", issuer="Inc42 (cites a Bernstein report; unnamed sources)", date="2026 (about one month before 30 Sep 2026)", url="https://inc42.com/features/zeptos-retention-play-fewer-discounts-premium-carts-a-paid-club/"),
    dict(id="S10", title="Zepto IPO page (SKU and retention figures attributed to the draft filing)", issuer="Groww", date="2026-08-02", url="https://groww.in/ipo/zepto-ipo"),
]

MEDIA_CLAIMS = [
    dict(id="M01", media_source="S06 (Inc42)", claim="UDRHP acknowledges low switching costs and pricing pressure",
         check="Checked against UDRHP-I Risk Factors (pp. 30-32): filing discloses competitor promotions, incentives, alternative pricing models and merchant/delivery multi-homing as business risks. However, no explicit statement establishing 'customers have low switching costs' is present.",
         status="NOT VERIFIED AS WORDED / CONTEXTUALIZED", action="Classify as unverified as worded; contextualize with disclosed competitive risks (Risk Factor 6, p. 31)"),
    dict(id="M02", media_source="S10 (Groww)", claim="Average SKUs per dark store rose from 12,312 (FY24) to 46,623 (FY26)",
         check="Verified on UDRHP-I printed p. 162 (Basis for Offer Price) and p. 538 (MD&A). SKUs at store geography level: 12,312 (FY24), 44,341 (FY25), 46,623 (FY26), reaching 49,602 in Q4 FY26.",
         status="VERIFIED - PRIMARY UDRHP KPI", action="Upgrade to verified primary KPI (S01 p. 162, p. 538)"),
    dict(id="M03", media_source="S10 (Groww)", claim="45.2-49.8% of users remain active three years after first order",
         check="Verified cohort-specific retention observations in UDRHP-I printed pp. 253-254 (Our Business). Exact observations: FY23 Q2 cohort retention was 45.2% in Q12 (Year 3) and 44.3% in Q15; FY23 Q3 was 48.1% in Q14; FY24 Q1 was 49.8% in Q9. Multi-year cohorts descriptively stabilize between 44.3% and 54.0%.",
         status="VERIFIED - PRIMARY UDRHP COHORT EVIDENCE", action="Upgrade to verified cohort evidence (S01 pp. 253-254) with precise cohort/quarter wording"),
    dict(id="M04", media_source="S07 (Inc42)", claim="Zepto curtailed platform-wide discounts and launched a paid membership (Zepto Club)",
         check="Checked against UDRHP-I: Definitions (p. 13) and Our Business (p. 258) confirm 'Zepto Pass' as the official subscription membership program. 'Zepto Club' is not established in the filing.",
         status="DISPROVED/CONTRADICTED", action="Label disproved/contradicted; note Zepto Pass as official filing term"),
    dict(id="M05", media_source="Groww/others", claim="1,139 dark stores, up from 1,029 (FY25) and 337 (FY24)",
         check="Verified on UDRHP-I printed p. 163 and S09 p. 13: closing store counts 337 (FY24), 1,029 (FY25), 1,139 (FY26 across 66 cities).",
         status="VERIFIED - PRIMARY UDRHP KPI", action="Upgrade to primary KPI (S01 p. 163 / S09 p. 13)"),
    dict(id="M06", media_source="Several outlets", claim="ATU 47.97 million at 31 Mar 2026 (10.57m FY24, 38.38m FY25)",
         check="Verified on UDRHP-I printed p. 160 and S09 pp. 2, 13: Annual Transacting Users (ATU) was 10.57m (FY24), 38.38m (FY25), 47.97m (FY26). Maintained as platform scale/adoption metric.",
         status="VERIFIED - PRIMARY UDRHP KPI", action="Upgrade to primary KPI (S01 p. 160 / S09 pp. 2, 13)"),
    dict(id="M07", media_source="Groww", claim="Order volume CAGR about 119.5% FY24-FY26",
         check="Verified on UDRHP-I printed p. 3 and S09 p. 3 quoting company-commissioned Redseer report.",
         status="VERIFIED - COMPANY-CITED REDSEER INDUSTRY EVIDENCE", action="Label as company-cited commissioned report statement (S01 p. 3)"),
    dict(id="M08", media_source="Outlook Business", claim="Rs 1,629 crore to open about 1,900 new dark stores; Rs 1,735 crore lease rentals through FY30",
         check="Verified on UDRHP-I printed pp. 143, 148 and S09 p. 5: Rs 16,289.75M for dark store expansion and Rs 17,349.41M for lease rentals.",
         status="VERIFIED - PRIMARY UDRHP OFFER/OBJECT DISCLOSURE", action="Upgrade to primary offer disclosure (S01 pp. 143, 148 / S09 p. 5)"),
    dict(id="M09", media_source="S06 (Inc42)", claim="Active user base fell from 49.54m (Dec 2025) to 47.97m (Mar 2026)",
         check="Verified on UDRHP-I printed p. 161 and S09 p. 11: trailing-12-month ATU dipped from 49.54m (31 Dec 2025) to 47.97m (31 Mar 2026), while orders/day rose 28.6% QoQ.",
         status="VERIFIED - PRIMARY UDRHP KPI", action="Upgrade to primary KPI (S01 p. 161 / S09 p. 11)"),
    dict(id="M10", media_source="S10 (Groww)", claim="Retained users purchase from over 18 product categories within two years",
         check="Verified on UDRHP-I printed p. 252 (Our Business): text confirms users expand from ~6 categories in Month 1 to >12 in Year 1 and 18 product categories within 2 years of joining.",
         status="VERIFIED - PRIMARY UDRHP BUSINESS DISCLOSURE", action="Upgrade to primary business disclosure (S01 p. 252)"),
    dict(id="M11", media_source="S06/others", claim="Delivery partners operate across multiple platforms; market follows the most aggressive pricer",
         check="Verified on UDRHP-I printed pp. 27-28 and p. 56 (Risk Factor 13): filing notes delivery partners have flexibility to join/leave at convenience and multi-home across multiple platforms.",
         status="VERIFIED - COMPANY RISK DISCLOSURE", action="Upgrade to verified company risk disclosure (S01 pp. 27-28, 56)"),
]

PRIMARY_ITEMS = [
    dict(source="S01", page="24", section="Section II: Risk Factors", claim="Rapid scaling resulted in net losses; revenue grew from Rs 44,545.16M (FY24) to Rs 226,235.84M (FY26) while restated net loss was Rs 59,051.92M (FY26) driven by network expansion and delivery expenses", construct="Operational context; cost-to-serve",
         evidence_type="Company risk disclosure", relation_to_survey="Cost floor limits long-term promotional price subsidization (context for H4)", status="Verified", use="Financial constraint on price promotions",
         claim_owner="Zepto Limited", survey_relation_type="Contextualizes"),
    dict(source="S01", page="27-28", section="Section II: Risk Factors", claim="Failure to attract and retain delivery partners cost-effectively diminishes fulfillment speed; active delivery partners grew to 221,667 (FY26) from 49,278 (FY24) with delivery expenses at 12.28% of NRV", construct="Service / experience",
         evidence_type="Company risk disclosure", relation_to_survey="Fleet capacity constraints directly impact delivery SLA/speed (context for H1 and former speed exits)", status="Verified", use="Operational risk context",
         claim_owner="Zepto Limited", survey_relation_type="Contextualizes"),
    dict(source="S01", page="30", section="Section II: Risk Factors", claim="Merchant partners multi-home across competing platforms and may reduce inventory on Zepto if rival terms or sales volumes are superior", construct="Switching / competitive dynamics; assortment",
         evidence_type="Company risk disclosure", relation_to_survey="Supply-side multi-homing directly creates assortment stock-outs (context for H3 and former voluntary availability exits)", status="Verified", use="Supply-side switching risk",
         claim_owner="Zepto Limited", survey_relation_type="Contextualizes"),
    dict(source="S01", page="31", section="Section II: Risk Factors", claim="Competitors may offer discounted services, user incentives, promotions, alternative pricing models, wider product selections, or retain users more effectively", construct="Competitor pull; promotions; pricing",
         evidence_type="Company risk disclosure", relation_to_survey="Directly contextualizes H2 (pull), H3 (variety), and H4 (promotions) as top disclosed strategic threats", status="Verified", use="Triangulation of competitor pull factor",
         claim_owner="Zepto Limited", survey_relation_type="Contextualizes"),
    dict(source="S01", page="34", section="Section II: Risk Factors", claim="If user-facing operating or logistics fees increase it may decrease the frequency with which users transact on the platform", construct="Price sensitivity; order frequency",
         evidence_type="Company risk disclosure", relation_to_survey="Directly links user fee sensitivity to transaction velocity and churn risk", status="Verified", use="Fee sensitivity context",
         claim_owner="Zepto Limited", survey_relation_type="Contextualizes"),
    dict(source="S01", page="44", section="Section II: Risk Factors", claim="Dark store network must be expanded cost-effectively; failure to deploy expansion proceeds effectively could impair growth and market coverage", construct="Coverage / availability",
         evidence_type="Company risk disclosure", relation_to_survey="Survey identifies coverage as a major reported barrier, while UDRHP independently documents expansion intended to extend serviceability (context for Class A former and never users)", status="Verified", use="Triangulation of coverage constraint",
         claim_owner="Zepto Limited", survey_relation_type="Contextualizes"),
    dict(source="S01", page="143-145", section="Section III: Objects of the Offer", claim="Gross proceeds earmarked include Rs 16,289.75M for setting up new dark stores in existing and new geographies over FY27-FY29", construct="Coverage / availability",
         evidence_type="Offer/object disclosure", relation_to_survey="Capital allocation aligns with survey evidence that unserved areas represent a major usage barrier (R1 context)", status="Verified", use="R1 feasibility context",
         claim_owner="Zepto Limited", survey_relation_type="Contextualizes"),
    dict(source="S01", page="148-150", section="Section III: Objects of the Offer", claim="Net proceeds allocated include Rs 17,349.41M for lease rentals of existing dark store network through FY30", construct="Coverage / infrastructure",
         evidence_type="Offer/object disclosure", relation_to_survey="Sustaining physical real estate in existing high-density catchments to preserve current user retention", status="Verified", use="Operational coverage stability",
         claim_owner="Zepto Limited", survey_relation_type="Contextualizes"),
    dict(source="S01", page="154-156", section="Section III: Objects of the Offer", claim="Net proceeds allocated include Rs 4,000.00M for investment in technology and cloud infrastructure supporting search, recommendations, and forecasting", construct="Loyalty / CRM; technology",
         evidence_type="Offer/object disclosure", relation_to_survey="Technical capital funding enablers for CRM Recommendation R2 (assortment/stock-out personalization) (CRM interpretation/inference)", status="Verified", use="R2 feasibility context",
         claim_owner="Zepto Limited", survey_relation_type="Contextualizes"),
    dict(source="S01", page="156-157", section="Section III: Objects of the Offer", claim="Net proceeds allocated include Rs 5,200.00M for marketing and business promotion through subsidiary Zepto Marketplace Private Limited", construct="Customer acquisition",
         evidence_type="Offer/object disclosure", relation_to_survey="Top-of-funnel customer acquisition budget balancing retention initiatives", status="Verified", use="Acquisition budget context",
         claim_owner="Zepto Limited", survey_relation_type="Contextualizes"),
    dict(source="S01", page="160", section="Section III: Basis for Offer Price", claim="Annual Transacting Users (ATU) grew from 10.57M (FY24) to 38.38M (FY25) to 47.97M (FY26). Maintained as platform scale/adoption KPI.", construct="Acquisition / scale",
         evidence_type="Company KPI", relation_to_survey="Population scale context; trailing-12-month unique user metric (does not measure individual churn)", status="Verified", use="Scale metric context",
         claim_owner="Zepto Limited", survey_relation_type="Contextualizes"),
    dict(source="S01", page="161", section="Section III: Basis for Offer Price", claim="Orders per day rose +28.6% QoQ to 2,333,488 in Q4 FY26 (from 1,814,288 in Q3 FY26) while trailing-12-month ATU dipped 3.2% from 49.54M to 47.97M", construct="Operational context; order frequency",
         evidence_type="Company KPI", relation_to_survey="Active cohort ordering frequency increased even as trailing 12-month unique transacting count stabilized", status="Verified", use="Usage frequency context",
         claim_owner="Zepto Limited", survey_relation_type="Contextualizes"),
    dict(source="S01", page="162", section="Section III: Basis for Offer Price", claim="Store-level unique SKUs grew from 12,312 (FY24) to 44,341 (FY25) to 46,623 (FY26) (Media Claim M02 verified)", construct="Product / assortment",
         evidence_type="Company KPI", relation_to_survey="Contextualizes H3 (variety) and voluntary former-user variety exits (8/32)", status="Verified", use="Triangulates assortment expansion",
         claim_owner="Zepto Limited", survey_relation_type="Contextualizes"),
    dict(source="S01", page="163", section="Section III: Basis for Offer Price", claim="Dark store network expanded from 337 stores across 11 cities (FY24) to 1,029 across 43 cities (FY25) to 1,139 across 66 cities (FY26)", construct="Coverage / availability",
         evidence_type="Company KPI", relation_to_survey="Quantifies geographic footprint expansion into non-metro cities (context for former Class A and never users)", status="Verified", use="Coverage scale context",
         claim_owner="Zepto Limited", survey_relation_type="Contextualizes"),
    dict(source="S01", page="194-196", section="Section IV: Industry Overview", claim="Indian quick commerce grew from ~Rs 133B (CY2022) to ~Rs 963B (CY2025), representing ~95% growth; accounts for >2/3 of online grocery orders and ~13% of online retail GMV (source: company-commissioned Redseer Report)", construct="Market context",
         evidence_type="Company-Cited Industry Evidence", relation_to_survey="Macro category adoption context across all competing platforms", status="Verified as quoted; commissioned source", use="Macro market context; do not restate as CAGR",
         claim_owner="Zepto filing quoting a Zepto-commissioned Redseer report", survey_relation_type="Contextualizes"),
    dict(source="S01", page="202-205", section="Section IV: Industry Overview", claim="Quick commerce consumer adoption expanding beyond grocery into beauty, personal care, electronics, and general merchandise (source: company-commissioned Redseer Report)", construct="Product / assortment; category expansion",
         evidence_type="Company-Cited Industry Evidence", relation_to_survey="Industry structural shift enabling cross-category basket growth (M10 context)", status="Verified as quoted; commissioned source", use="Category expansion context",
         claim_owner="Zepto filing quoting a Zepto-commissioned Redseer report", survey_relation_type="Contextualizes"),
    dict(source="S01", page="234-235", section="Section IV: Our Business", claim="Platform operates on S.Q.A.P. customer experience framework (Speed, Quality, Assortment, Price transparency) supported by Everyday Low Price (EDLP) philosophy", construct="Assortment; price; value proposition",
         evidence_type="Company Business Disclosure", relation_to_survey="Internal strategic positioning designed to reduce push factors and build customer stickiness", status="Verified", use="Platform positioning context",
         claim_owner="Zepto Limited", survey_relation_type="Contextualizes"),
    dict(source="S01", page="246-247", section="Section IV: Our Business", claim="In-house search and recommendations engine utilizes machine learning models for user intent parsing, query understanding, and catalog ranking", construct="Loyalty / CRM; personalization",
         evidence_type="Company Business Disclosure", relation_to_survey="Confirms existing algorithmic capability supporting CRM Recommendation R2 (CRM interpretation/inference)", status="Verified", use="R2 feasibility context",
         claim_owner="Zepto Limited", survey_relation_type="Contextualizes"),
    dict(source="S01", page="252", section="Section IV: Our Business", claim="New users purchase from an average of ~6 categories in Month 1, expanding to >12 categories in Year 1 and 18 product categories in Year 2 (Media Claim M10 verified)", construct="Customer retention; category expansion",
         evidence_type="Company Business Disclosure", relation_to_survey="Cross-category purchasing depth is identified as a descriptive marker of multi-year user stickiness", status="Verified", use="Retention marker context",
         claim_owner="Zepto Limited", survey_relation_type="Contextualizes"),
    dict(source="S01", page="253-254", section="Section IV: Our Business", claim="User cohort retention matrix shows quarterly active ordering stabilizes between 44.3% and 54.0% across multi-year cohorts (e.g. FY23 Q2 cohort retention was 45.2% in Q12/Year 3 and 44.3% in Q15; FY24 Q1 was 49.8% in Q9; Media Claim M03 verified)", construct="Customer retention / loss",
         evidence_type="Company KPI", relation_to_survey="Empirical industry benchmark showing ~50% initial cohort attrition before multi-year stabilization", status="Verified", use="Retention baseline context",
         claim_owner="Zepto Limited", survey_relation_type="Contextualizes"),
    dict(source="S01", page="258-259", section="Section IV: Our Business", claim="Zepto Pass is the official subscription membership program offering delivery perks and promotions; 'Zepto Club' is not established in the filing", construct="Loyalty / CRM",
         evidence_type="Company Business Disclosure", relation_to_survey="Subscription loyalty tool to build platform mooring (context for H5/H6 and R4)", status="Verified", use="Loyalty program context",
         claim_owner="Zepto Limited", survey_relation_type="Contextualizes"),
    dict(source="S01", page="260-261", section="Section IV: Our Business", claim="Dark store network densification reduces average delivery radius, targeting under 10-15 minute delivery fulfillment", construct="Service / experience; delivery speed",
         evidence_type="Company Business Disclosure", relation_to_survey="Addresses delivery speed expectations (context for former-user delivery reasons)", status="Verified", use="Delivery SLA context",
         claim_owner="Zepto Limited", survey_relation_type="Contextualizes"),
    dict(source="S01", page="530-532", section="Section V: MD&A", claim="Supply Chain Variable Cost per Order defines variable fulfilment and delivery costs per order, establishing unit economic boundaries", construct="Operational context; unit economics",
         evidence_type="Company/MD&A Disclosure", relation_to_survey="Cost floor below which promotional free delivery cannot be sustainably extended", status="Verified", use="Unit economics context",
         claim_owner="Zepto Limited", survey_relation_type="Contextualizes"),
    dict(source="S01", page="538", section="Section V: MD&A", claim="Management explicitly links assortment growth (reaching 49,602 SKUs in Q4 FY26) and EDLP pricing to improved user value proposition and retention", construct="Assortment; retention strategy",
         evidence_type="Company/MD&A Disclosure", relation_to_survey="Management strategy aligns with survey finding that variety and price are primary voluntary exit/pull levers", status="Verified", use="Management retention perspective",
         claim_owner="Zepto Limited", survey_relation_type="Contextualizes"),
    dict(source="S01", page="545-547", section="Section V: MD&A", claim="Advertising and sales promotion expenses tracked across city rollouts to drive customer acquisition across 66 cities", construct="Price / promotion; acquisition spend",
         evidence_type="Company/MD&A Disclosure", relation_to_survey="Captures customer acquisition expenditure supporting brand rollout", status="Verified", use="Acquisition spend context",
         claim_owner="Zepto Limited", survey_relation_type="Contextualizes"),
]

INDUSTRY_ITEMS = [
    dict(source="S03", page="n/a", section="Full article (12 Feb 2026)", claim="January 2026: quick-commerce GMV about Rs 11K crore (about 100% YoY); about 7.8 million orders/day (about +95% YoY); AOV (post MRP discounts, excluding delivery fees) about Rs 460; monthly transacting users about 5.2 crore (about +95% YoY); dark stores about 6,280 (from about 5,990 in Dec 2025)", construct="Market context",
         evidence_type="Independent industry (Redseer), full article read; proprietary Benchmarks data", relation_to_survey="Context only", status="Verified (as published by Redseer)", use="Market context",
         claim_owner="Redseer (independent public article; not Zepto-specific)", survey_relation_type="Contextualizes"),
    dict(source="S03", page="n/a", section="Full article (12 Feb 2026)", claim="Redseer says competitive pressure is building: the top three platforms grow about 75% YoY in GMV while challenger platforms grow about 4x faster, with visible share movement at the margin", construct="Competition",
         evidence_type="Independent industry (Redseer)", relation_to_survey="Industry-level competition, not user switching; no retention or churn data given", status="Verified", use="Context for competitor-pull factor",
         claim_owner="Redseer (independent public article; not Zepto-specific)", survey_relation_type="Contextualizes"),
    dict(source="S04", page="n/a", section="Full article (3 Jul 2025)", claim="Non-metro cities (90+) contribute just over 20% of quick-commerce GMV; orders per dark store fall below 1,000 beyond the top 10-15 cities; Redseer cites nascent users with low digital trust, lower density and localised tastes and advises prioritising cities and refining assortment, pricing and marketing there", construct="Coverage; assortment",
         evidence_type="Independent industry (Redseer analysis)", relation_to_survey="Independent context that footprint and local assortment are strategic issues; says nothing about individual user exits", status="Verified", use="Context for R1/R2",
         claim_owner="Redseer (independent public article; not Zepto-specific)", survey_relation_type="Contextualizes"),
    dict(source="S05", page="n/a", section="Full article (19 Nov 2025)", claim="As of July 2025, about 33 million monthly transacting users across 150+ cities; users are typically Gen-Z/millennial from affluent metro/Tier-1 households; Redseer describes users as more time-sensitive than price-sensitive (brand-strategy context)", construct="Market context; price sensitivity",
         evidence_type="Independent industry (Redseer); not Zepto-specific", relation_to_survey="User profile is similar in age band to the survey sample; price-sensitivity statement is general", status="Verified", use="Context (S03's Jan 2026 MTU of about 5.2 crore is a later date)",
         claim_owner="Redseer (independent public article; not Zepto-specific)", survey_relation_type="Contextualizes"),
]

STATS_REGISTER = [
    ("Commissioned Redseer report (30 May 2026): market structure and growth drivers", "S02", "Commissioned industry report", "Standalone report not retrieved independently; figures quoted from UDRHP-I (S01) and S09"),
    ("Quick-commerce market ~Rs 133bn (CY2022) -> ~Rs 963bn (CY2025), '~95% growth' (not labelled CAGR); ~13% of online retail GMV CY2025", "Redseer Report as quoted in UDRHP-I pp. 194-196 and S09 p.3", "Primary filing quoting commissioned report", "Checked against UDRHP-I text; company-cited, not independent"),
    ("ATU 47.97m (31 Mar 2026), +25.00% YoY; 49.54m at 31 Dec 2025; 10.57m FY24, 38.38m FY25", "UDRHP-I pp. 160-161, S09 pp. 2, 11, 13", "Primary filing KPI", "Checked against UDRHP-I tables; platform scale metric"),
    ("1,139 dark stores, 75 warehouses (31 Mar 2026); closing stores 337 / 1,029 / 1,139 (FY24/25/26)", "UDRHP-I p. 163, S09 pp. 3, 13", "Primary filing KPI", "Checked against UDRHP-I tables"),
    ("Orders per day 2,333,488 (Q4 FY26) vs 1,814,288 (Q3 FY26)", "UDRHP-I p. 161, S09 p. 11", "Primary filing KPI", "Checked against UDRHP-I tables"),
    ("Dark-store expansion Rs 16,289.75m; lease rentals Rs 17,349.41m; marketing Rs 5,200m", "UDRHP-I pp. 143, 148, 156, S09 p. 5", "Primary filing Offer/Object disclosure", "Checked against UDRHP-I tables"),
    ("Store-level unique SKUs: 12,312 (FY24) -> 44,341 (FY25) -> 46,623 (FY26) -> 49,602 (Q4 FY26)", "UDRHP-I p. 162, p. 538", "Primary filing KPI", "Checked against UDRHP-I tables; Media Claim M02 verified"),
    ("Cohort retention: FY23 Q2 was 45.2% in Q12 (Year 3), 44.3% in Q15; FY23 Q3 48.1% in Q14; FY24 Q1 49.8% in Q9; descriptive multi-year range 44.3%-54.0%", "UDRHP-I pp. 253-254", "Primary filing KPI", "Checked against UDRHP-I cohort matrix; Media Claim M03 verified"),
    ("Purchasing category expansion: ~6 categories in Month 1 -> >12 in Year 1 -> 18 categories in Year 2", "UDRHP-I p. 252", "Primary filing business disclosure", "Checked against UDRHP-I text; Media Claim M10 verified"),
    ("Jan 2026 GMV ~Rs 11K crore, ~7.8m orders/day, AOV ~Rs 460, MTU ~5.2 crore, ~6,280 dark stores", "S03 (Redseer, 12 Feb 2026)", "Independent industry (Redseer)", "Full article read"),
    ("~33 million MTUs across 150+ cities (as of July 2025)", "S05 (Redseer, 19 Nov 2025)", "Independent industry (Redseer)", "Full article read; earlier date than the 5.2 crore in S03"),
    ("Non-metro 90+ cities just over 20% of GMV; OPD per dark store below 1,000 beyond top 10-15 cities", "S04 (Redseer, 3 Jul 2025)", "Independent industry (Redseer)", "Full article read"),
]


def run(res: dict = None):
    C.LIT.mkdir(parents=True, exist_ok=True); C.SEC.mkdir(parents=True, exist_ok=True)
    lit = pd.DataFrame(LITERATURE)
    lit.to_csv(C.LIT / "references.csv", index=False)
    pd.DataFrame(EXCLUDED_CANDIDATES).to_csv(C.LIT / "excluded_candidates.csv", index=False)
    he = pd.DataFrame([
        dict(H="H1", relation="Satisfaction -> switching intention (-)", evidence_class="Mixed evidence",
             supporting="L16 (B): push factors (service, product issues, technical issues, price perception) significant; L06 (B): push positive (retailers); L01 (B) generic", mixed_or_contrary="L05 (A): satisfaction -> intention 0.071, not significant; L10 (A): dissatisfaction -> intention 0.127, p=.069, not significant",
             note="Two full-text studies show non-significant satisfaction/dissatisfaction effects; a null here is not surprising"),
        dict(H="H2", relation="Alternative attractiveness -> switching intention (+)", evidence_class="Direct empirical support", supporting="L05 (A): 0.328; L10 (A): 0.314; L16 (B): alternative attraction significant", mixed_or_contrary="none retrieved",
             note="L10 concerns channel adoption (physical market to e-grocery); L05 and L16 are platform/retailer switching"),
        dict(H="H3", relation="Competitor product choice/variety -> intention (+)", evidence_class="Indirect/theoretical support", supporting="L05 (A): attractiveness scale includes 'other platforms better meet my needs'; L16 (B): alternative attraction", mixed_or_contrary="none",
             note="No verified study isolates perceived competitor variety as a separate predictor"),
        dict(H="H4", relation="Competitor promotions -> intention (+)", evidence_class="Indirect/theoretical support", supporting="L05 (A): one attractiveness item concerns deals/promotions", mixed_or_contrary="none", note="Measurement precedent only; no isolated promotion effect verified"),
        dict(H="H5", relation="Switching effort -> intention (-)", evidence_class="Mixed evidence", supporting="L04 (C): typology; L01 (B): mooring effects generic; L16 (B): switching cost moderates", mixed_or_contrary="L10 (A): switching cost -> intention +0.294 (positive; items concern effort of changing to the alternative); L06 (B): switching cost not significant; L17 (B): lower switching costs strengthen the pull effect (moderation)",
             note="No verified study showing the hypothesised negative direct effect was retrieved; the present positive sign has a verified full-text precedent (different context)"),
        dict(H="H6", relation="Familiarity -> intention (-)", evidence_class="Insufficient evidence", supporting="L11 (B): habit toward traditional stores -0.136 (abstract)", mixed_or_contrary="none", note="Abstract-level only; habit toward the origin channel differs from familiarity with Zepto"),
        dict(H="H7", relation="Inertia -> intention (-)", evidence_class="Direct empirical support (abstract-level only)", supporting="L15 (B): inertia negatively affects switching intention (abstract); L08 (B): inertia moderates (abstract)", mixed_or_contrary="none", note="Abstract-level; service-channel contexts; not full-text verified"),
        dict(H="H8", relation="Joint PPM composites explain intention variance", evidence_class="Indirect/theoretical support", supporting="L05 (A): about 42% variance with different constructs", mixed_or_contrary="none", note="Present R2 is inflated by item overlap"),
        dict(H="H9", relation="Intention associated with partial actual switching", evidence_class="No verified evidence", supporting="No directly verified study was identified in the search conducted", mixed_or_contrary="n/a", note="Study-specific extension"),
        dict(H="H10", relation="Coverage-driven exits more willing to return than voluntary leavers", evidence_class="No verified evidence", supporting="No directly verified study was identified in the search conducted", mixed_or_contrary="n/a", note="Study-specific extension"),
    ])
    he.to_csv(C.LIT / "hypothesis_evidence.csv", index=False)
    src = pd.DataFrame(SOURCES)
    src.to_csv(C.SEC / "sources.csv", index=False)
    pd.DataFrame(MEDIA_SOURCES).to_csv(C.SEC / "media_sources_not_evidence.csv", index=False)
    pd.DataFrame(MEDIA_CLAIMS).to_csv(C.SEC / "media_claims_register.csv", index=False)
    
    ev = pd.DataFrame(PRIMARY_ITEMS + INDUSTRY_ITEMS)
    ev.to_csv(C.SEC / "evidence_matrix.csv", index=False)
    pd.DataFrame(PRIMARY_ITEMS).to_csv(C.TABLES / "table16_zepto_secondary_evidence.csv", index=False)
    pd.DataFrame(INDUSTRY_ITEMS).to_csv(C.TABLES / "table17_industry_secondary_evidence.csv", index=False)
    pd.DataFrame(STATS_REGISTER, columns=["statistic", "source", "source_type", "verification_status"]).to_csv(C.SEC / "statistics_register.csv", index=False)
    return lit, he, src, ev
